---

all:
  hosts:
    vm1:
      ansible_host: 192.168.102.2
    vm2:
      ansible_host: 192.168.103.2
    vm3:
      ansible_host: 192.168.100.139

webservers:
  hosts:
    vm1:
      ansible_host: 192.168.102.2
    vm2:
      ansible_host: 192.168.103.2
    vm3:
      ansible_host: 192.168.100.139

# [all:vars]
# ansible_ssh_user="javid"