# - hosts: all
#   become: true
#   tasks:

#   - name: install apache and php packages
#     ansible.builtin.apt:
#       name: 
#         - apache2
#         - libapache2-mod-php
#       state: latest
#       update_cache: true
#       cache_valid_time: 3600
#     when: ansible_distribution in ["Ubuntu", "Debian"]

# - hosts: all
#   become: true
#   tasks:
#   - name: install httpd and php packages
#     ansible.builtin.dnf:
#       name: "{{ item }}"
#       state: latest
#       update_cache: true
#     loop:
#       - httpd
#       - php
#     when: ansible_distribution in ["Centos", "Rocky", "Fedora", "rhel"]

- name: install apache and php
  ansible.builtin.package:
    name: 
      - "{{ webservice }}"
      - "{{ php }}"
    state: latest