---

# - name: install apache and php
#   ansible.builtin.package:
#     name: 
#       - "{{ item.service }}"
#       - "{{ item.php }}"
#     state: latest
#   with_items: '{{ webservers }}'

- name: install apache and php (rhel based distro)
  ansible.builtin.dnf:
    name:
      - "{{service_rh}}"
      - "{{php_rh}}"
    state: latest
  when: ansible_distribution in ["Centos", "Rocky"]

- name: install apache and php (debian based distro)
  ansible.builtin.apt:
    name:
      - "{{service_deb}}"
      - "{{php_deb}}"
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]


...