---

- name: updates (dnf)
  ansible.builtin.dnf:
    update_cache: true
    #update_only: true
    autoremove: true
  when: ansible_distribution in ["Centos", "Rocky"]

- name: updates and upgrade (apt)
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
    #only_upgrade: true
    autoremove: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

...